### ISSUE TITLE
Roadmap to 1.0.0

### ISSUE THREAD

**Issue by azirbel** [Addepar/ember-table#120]
## Introduction and Motivation

Ember-table has come a long way since it was started a little over a year ago. Thanks so much to the amazing people in the Ember community who have helped the project get this far - it wouldn't have happened without you!

A lot of hard work has gone into ember-table, and it should be as easy as possible for anyone to build off that work. Below, we've put together a list of improvements designed to make the project more usable and approachable for new members of the community. Everything here is open to discussion - think this list is missing an important priority, or has some unnecessary goals? Comment and I'll edit the roadmap.

Most of what's here is based on a few key ideas:
- Ember-table needs a proper versioning system to make sure its users can get updates easily without being as worried about breaking changes. Moving the project to Semantic Versioning ([semver.org](http://semver.org/)), the same system Ember uses, would accomplish this. The roadmap should include the critical work we need to do before we're ready to release version 1.0.0.
- Adding tests will allow contributors to be confident their changes aren't breaking functionality others depend on.
- The project should be easier for others to use: we should manage ember-table dependencies, and make sure others can manage their ember-table dependency, using bower.
### Dependencies and Versioning
- [x] Manage ember-table's dependencies via bower
- [x] Set up versioning system ([semver.org](http://semver.org/))
- [x] Make it easy to download a specific version of ember-table via bower
### Documentation
- [x] Document contribution policies
- [x] Document versioning system ([semver.org](http://semver.org/))
- [ ] Set up version-specific documentation
- [ ] Ensure documentation reflects the correct API for version 1.0.0
- [x] Add a changelog, to be edited with every release
### Testing
- [ ] Add a few sample tests
- [ ] Document testing policy (new code should be tested)
### General Cleanup
- [x] Delete all outdated non-master branches
- [ ] Close all enhancement issues which will be part of this roadmap
- [ ] Respond to all issues tagged "question"
### Ember CLI and Modules
- [ ] Allow for easy importing in ember-cli projects, using module syntax
- [ ] Publish to npm
## Some final comments

Not every high-priority issue for ember-table is listed here; this is intended to be a minimal list focused on making it more available to the community.

Have any feedback? Leave a comment and start a discussion! Able to work on any of this? Fantastic - send in a PR (optionally, post a comment so others know you're working on it) - we'll make it a priority to merge it in. What's described here is an idea; it'll take a community effort to make it real.

**Comment by ohcibi** [comment]
+1 for using components. Controllers and Views will be gone soon, so the incompatibilities with future ember versions will increase. I'd also vote for not supporting too much old ember versions as this slows the process of catching up with recent changes (like the situation we are in right now. There are issues speaking about handlebars-2.0 but ember is at HTMLbars already, I did not find any mention of HTMLbars in #227). Please make converting to components and moving on the ember-1.10+ a high priority task.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
