### ISSUE TITLE
Ember Table 2.0.0-beta.1 Roadmap

### ISSUE THREAD

**Issue by pzuraq** [Addepar/ember-table#520]
This issue is for tracking progress towards the first beta of 2.0.0

### Goals

- **Feature parity with Ember Table 1 usage at Addepar**

  This includes many features _not_ in Ember Table 1 that have been added internally such as tree data structure support, subcolumns, and sorting

- **Configurable and customizable at any level**

  Ember Table 1 encouraged users to extend its component/view classes to add simple features like class names, customized templates, event handlers, etc. Ember Table 2 should not require any extension to handle these things, it should be possible to customize them via the template and public APIs.

- **Accessible**

  Ember Table 1 was no accessible at all. We plan to have a base level of accesibility for the initial beta release, and to build on it in the future.

### Features

- [ ] Header
  - [x] ~Fixed header~
  - [x] ~Fixed columns (multiple, left and right)~
  - [x] ~Subcolumns (any configuration and any level of nesting)~
  - [x] ~Reorderable columns~
  - [x] ~Resizable columns~
  - [ ] Sorting API (multi-column sort, default sort function)
  - [x] ~Customizable via yields~
  - [x] ~Documentation~
- [ ] Body
  - [x] ~Occlusion for large lists~
  - [x] ~Tree data structure support~
  - [x] ~Collapsible rows~
  - [x] ~Selectable rows (multiple and single modes)~
  - [x] ~Cell caches (meta object to put temporary table state on)~
  - [x] ~Customizable via yields~
  - [ ] Documentation
- [ ] Footer
  - [x] ~Fixed Footer~
  - [x] ~Customizable via yields~
  - [ ] Documentation
- [x] ~General~
  - [x] ~A11y by using semantic HTML (`<table>` tag, etc)~
  - [x] ~Legacy browser support (IE11)~

### Tasks

- [ ] Convert to new API outlined in #505
- [x] ~Convert to using `position: sticky` for fixing headers/footers~
- [x] ~Add cell meta cache, column meta cache, and row meta cache~
- [x] ~Implement selectable rows~
- [x] ~Implement row tree data structure for wrapping simple rows~
- [x] ~Implement column tree data structure for wrapping simple columns~
- [ ] Implement multi-column sort and default sorting functionality
- [ ] Tests 
  - [x] Header
  - [ ] Body
  - [ ] Footer

The target API for beta.1 is outlined in #505:

```hbs
{{#ember-table as |t|}}
  {{#t.head columns=columns sortings=sortings as |h|}}
    {{#h.row as |r|}}
      {{#r.cell as |column|}}
        {{column.name}}
      {{/r.cell}}
    {{/h.row}}
  {{/t.head}}

  {{#t.body rows=rows as |b|}}
    {{#b.row as |r|}}
      {{#r.cell as |value cell column row|}}
        {{value}}
      {{/r.cell}}
    {{/b.row}}
  {{/t.body}}

  {{#t.foot rows=rows as |f|}}
    {{#f.row as |r|}}
      {{#r.cell as |value cell column row|}}
        {{value}}
      {{/r.cell}}
    {{/f.row}}
  {{/t.foot}}
{{/ember-table}}
```

**Comment by wuarmin** [comment]
hello @pzuraq,
I'm migrating ember-table to new api. I have to customize the headers. Is it considered as good to derive my custom-header from ember-th?

**Comment by wuarmin** [comment]
Hello @pzuraq,
I'm migrating to ember-table's new api and have some styling-issues. Should we define @addepar/style-toolbox as dependency?

**Comment by pzuraq** [comment]
`@addepar/style-toolbox` is our in-progress style framework. It’s tailored specifically to Addepar, and changing pretty frequently at the moment, so it may not be the best to rely on. If you like the look of the styles for the table, feel free to use them.

In general, Ember Table only includes the absolute minimum styles that are required for it to work. This allows you to add whatever styles you like. You can use our style framework as an example, but develop your own if you like. We cannot guarantee that our style framework will have the same semver guarantees as Ember Table, so this is probably the best approach.

**Comment by wuarmin** [comment]
@pzuraq thank you for the clarification :)

**Comment by pzuraq** [comment]
Beta 1 has been launched!
